work_dir: /data2/guoty/CACA-work-dir/CACA-STGCN/pkup2cs/3views/512_2048_512_2048_0.996_2_10/linear_eval_ep250

# weights: /data2/guoty/CACA-work-dir/CACA-STGCN/pkup2cs/3views/512_2048_512_2048_0.996_2_10/pretext/epoch250_model.pt
weights: ./model/pkup2_cs_53.48.pt
ignore_weights: [online_projector_joint, target_backbone_joint, target_projector_joint, online_predictor_joint, online_projector_motion, target_backbone_motion, target_projector_motion, online_predictor_motion, online_projector_bone, target_backbone_bone, target_projector_bone, online_predictor_bone]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: /data1/gty/action_dataset/pku_part2_frame50/xsub/train_position.npy
  label_path: /data1/gty/action_dataset/pku_part2_frame50/xsub/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /data1/gty/action_dataset/pku_part2_frame50/xsub/val_position.npy
  label_path: /data1/gty/action_dataset/pku_part2_frame50/xsub/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.caca_three_modal.CACA_3views
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  feature_dim: 512
  # projection_hidden_size: 2048
  # projection_size: 2048
  # prediction_hidden_size: 512
  # moving_average_decay: 0.99
  # use_momentum: True
  in_channels: 3
  hidden_channels: 16 # 1/4 x channels of standard stgcn
  num_class: 51
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 0.0
base_lr: 3.
optimizer: SGD
step: [80]

# training
device: [4]
batch_size: 128
test_batch_size: 128
num_epoch: 100
stream: 'all'

# log
save_interval: -1
eval_interval: 5
