work_dir: /data2/guoty/CACA-work-dir/CACA-STGCN/ntu60_cv/motion/512_2048_512_2048_0.996/pretext

# feeder
train_feeder: feeder.ntu_feeder.Feeder_dual
train_feeder_args:
  data_path: /data/gty/action_dataset/ntu60_frame50/xview/train_position.npy
  label_path: /data/gty/action_dataset/ntu60_frame50/xview/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True

# memory feeder for knn
mem_train_feeder: feeder.ntu_feeder.Feeder_single
mem_train_feeder_args:
  data_path: /data/gty/action_dataset/ntu60_frame50/xview/train_position.npy
  label_path: /data/gty/action_dataset/ntu60_frame50/xview/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
mem_test_feeder: feeder.ntu_feeder.Feeder_single
mem_test_feeder_args:
  data_path: /data/gty/action_dataset/ntu60_frame50/xview/val_position.npy
  label_path: /data/gty/action_dataset/ntu60_frame50/xview/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.caca_single_modal.CACA
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: True
  feature_dim: 512
  projection_hidden_size: 2048
  projection_size: 512
  prediction_hidden_size: 2048
  moving_average_decay: 0.996
  use_momentum: True
  in_channels: 3
  hidden_channels: 16 # 1/4 x channels of standard stgcn
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.1
optimizer: SGD
step: [300]

# training
device: [3]
batch_size: 128
test_batch_size: 128
num_epoch: 60
start_epoch: 0
stream: 'motion'

# log
save_interval: 5
eval_interval: -1

# knn
knn_monitor: True
knn_interval: 5
