work_dir: /data2/guoty/CACA-work-dir/CACA-STGCN/ntu60_cv/bone/512_2048_512_2048_0.996/linear_eval_60_128

weights: /data2/guoty/CACA-work-dir/CACA-STGCN/ntu60_cv/bone/512_2048_512_2048_0.996/pretext/epoch60_model.pt
ignore_weights: [online_projector, target_backbone, target_projector, online_predictor]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: /data/gty/action_dataset/ntu60_frame50/xview/train_position.npy
  label_path: /data/gty/action_dataset/ntu60_frame50/xview/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /data/gty/action_dataset/ntu60_frame50/xview/val_position.npy
  label_path: /data/gty/action_dataset/ntu60_frame50/xview/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.caca_single_modal.CACA
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  feature_dim: 512
  # projection_hidden_size: 1024
  # projection_size: 256
  # prediction_hidden_size: 1024
  # moving_average_decay: 0.99
  # use_momentum: True
  in_channels: 3
  hidden_channels: 16 # 1/4 x channels of standard stgcn
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 0.0
base_lr: 3.
optimizer: SGD
step: [80]

# training
device: [3]
batch_size: 128
test_batch_size: 128
num_epoch: 100
stream: 'bone'

# log
save_interval: -1
eval_interval: 5
